Test02/Controllers/LoginUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Test02.Models;
namespace Test02.Controllers
{
    public class LoginUserController : Controller
    {
        QuanLyDLproEntities2 database = new QuanLyDLproEntities2();
        // GET: LoginUser
        public ActionResult Login()
        {
                return View();
        }
        [HttpPost]
        public ActionResult Login(string username, string password)
        {
            var kd = "NVKD"; var kho = "NVK";var kt = "NVKT";var gh = "NVGH"; var qtv = "QTHT";
            var data = database.NhanViens.Where(s => s.UserName == username && s.Password == password).FirstOrDefault();
            var taikhoan = database.NhanViens.SingleOrDefault(s => s.UserName == username && s.Password == password);
            if(data == null)
            {
                TempData["error"] = "Tài khoản đăng nhập không đúng";
                return View("Login");
            }
            else if(taikhoan != null)
            {
                //add session
                database.Configuration.ValidateOnSaveEnabled = false;
                Session["user"] = taikhoan;
                if (data.MaChucVu.ToString() == kd)
                {
                    return RedirectToAction("TrangChu", "KinhDoanh");
                }
                else if (data.MaChucVu.ToString() == kho)
                {
                    return RedirectToAction("Test02", "PhongKho");
                }
                else if (data.MaChucVu.ToString() == kt)
                {
                    return RedirectToAction("TrangChuKeToan", "KeToan");
                }
                else if (data.MaChucVu.ToString() == qtv)
                {
                    return RedirectToAction("QLNhanVien", "QTV");
                }
                else if (data.MaChucVu.ToString() == gh)
                {
                    return RedirectToAction("DonHangMoi", "GiaoHang");
                }
            }
            return View();
        }


        //Logout
        public ActionResult Logout()
        {
            Session.Clear();//remove session
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }
        //create a string MD5
        public static string GetMD5(string str)
        {
            MD5 md5 = new MD5CryptoServiceProvider();
            byte[] fromData = Encoding.UTF8.GetBytes(str);
            byte[] targetData = md5.ComputeHash(fromData);
            string byte2String = null;

            for (int i = 0; i < targetData.Length; i++)
            {
                byte2String += targetData[i].ToString("x2");

            }
            return byte2String;
        }
        public ActionResult QuenMK()
        {
            return View();
        }
    }
}

Test02/Views/LoginUser/Login.cshtml
@model Test02.Models.NhanVien
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Trang đăng nhập</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="~/Content/vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="~/Content/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="~/Content/vendor/animate/animate.css">
    <link rel="stylesheet" type="text/css" href="~/Content/vendor/css-hamburgers/hamburgers.min.css">
    <link rel="stylesheet" type="text/css" href="~/Content/vendor/select2/select2.min.css">
    <link rel="stylesheet" type="text/css" href="~/Content/css/util.css">
    <link rel="stylesheet" type="text/css" href="~/Content/css/main.css">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-sweetalert/1.0.1/sweetalert.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">
    <link rel="stylesheet" href="https://unpkg.com/boxicons@latest/css/boxicons.min.css">
</head>
<body>
    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100 row">
                <div class="login100-pic js-tilt col-lg-6" data-tilt>
                    <img src="~/Content/images/backgroungteam.png" alt="IMG">
                </div>
                <!--=====TIÊU ĐỀ======-->
                <div class="col-lg-6">
                    @using (Html.BeginForm("Login", "LoginUser", FormMethod.Post))
                    {

                        <span class="login100-form-title">
                            <b>ĐĂNG NHẬP HỆ THỐNG POS</b>
                        </span>
                        <!--=====FORM INPUT TÀI KHOẢN VÀ PASSWORD======-->
                        <div class="wrap-input100 validate-input">
                            <input class="input100" type="text" placeholder="Tài khoản quản trị" name="UserName"
                                   id="UserName">
                            <span class="focus-input100"></span>
                            <span class="symbol-input100">
                                <i class='bx bx-user'></i>
                            </span>
                        </div>
                        <div class="wrap-input100 validate-input">
                            <input autocomplete="off" class="input100" type="password" placeholder="Mật khẩu"
                                   name="Password" id="Password">
                            <span toggle="#password-field" id="spanElement" class="bx fa-fw bx-hide field-icon click-eye"></span>
                            <span class="focus-input100"></span>
                            <span class="symbol-input100">
                                <i class='bx bx-key'></i>
                            </span>
                        </div>
                        <p class="text-danger">@TempData["error"]</p>
                        <!--=====ĐĂNG NHẬP======-->
                        <div class="container-login100-form-btn">
                            <input type="submit" value="Đăng nhập" />
                        </div>
                        <!--=====LINK TÌM MẬT KHẨU======-->
                        <div class="text-right p-t-12">
                            <a class="txt2" href="~/LoginUser/QuenMK">
                                Bạn quên mật khẩu?
                            </a>
                        </div>
                    }
                </div>
               
                <!--=====FOOTER======-->
                <div class="text-center p-t-70 txt2">
                    Phần mềm quản lý đại lý <i class="far fa-copyright" aria-hidden="true"></i>
                    <script type="text/javascript">document.write(new Date().getFullYear());</script> <a class="txt2" href="https://www.facebook.com/nha.truong.3110567/"> Code bởi nhỏm G02_Quản Lý các đại lý (CNPM_Huflit) </a>
                </div>
            </div>
        </div>
    </div>
    <!--Javascript-->
    <script src="~/Content/js/main.js"></script>
    <script src="https://unpkg.com/boxicons@latest/dist/boxicons.js"></script>
    <script src="~/Content/vendor/jquery/jquery-3.2.1.min.js"></script>
    <script src="~/Content/vendor/bootstrap/js/popper.js"></script>
    <script src="~/Content/vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/Content/vendor/select2/select2.min.js"></script>
    <script type="text/javascript">
        //show - hide mật khẩu
        function myFunction() {
            var x = document.getElementById("myInput");
            if (x.type === "password") {
                x.type = "text"
            } else {
                x.type = "password";
            }
        }
        $(".click-eye").click(function () {
            $(this).toggleClass("bx-show bx-hide");
            var input = $($(this).attr("toggle"));
            if (input.attr("type") == "password") {
                input.attr("type", "text");
            } else {
                input.attr("type", "password");
            }
        });
        const ipnElement = document.querySelector('#Password')
        const spanElement = document.querySelector('#spanElement')
        // step 2
        spanElement.addEventListener('click', function () {
            // step 3
            const currentType = ipnElement.getAttribute('type')
            // step 4
            ipnElement.setAttribute(
                'type',
                currentType === 'password' ? 'text' : 'password'
            )
        })
    </script>

</body>
</html>

Test02/Views/LoginUser/QuenMK.cshtml
@{
    ViewBag.Title = "QuenMK";
    Layout = "~/Views/LoginUser/Layout/QuenMatKhau.cshtml";
}
<script src="~/Content/js/main.js"></script>