Test02/Controllers/LoginDLController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Test02.Models;
namespace Test02.Controllers
{
    public class LoginDLController : Controller
    {
        QuanLyDLproEntities2 database = new QuanLyDLproEntities2();
        // GET: LoginDL
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(string username, string password)
        {
            
            var data = database.DaiLies.Where(s => s.UserName == username && s.Password == password).FirstOrDefault();
            var taikhoan = database.DaiLies.SingleOrDefault(s => s.UserName == username && s.Password == password);
            
            if (data == null)
            {
                TempData["error"] = "Tài khoản đăng nhập không đúng";
                return View("Login");
            }
            else if (taikhoan != null)
            {
                //add session
                database.Configuration.ValidateOnSaveEnabled = false;
                Session["userDL"] = taikhoan;
                return RedirectToAction("PageSanPham", "KhachHang");
                
            }
            return View();
        }


        //Logout
        public ActionResult Logout()
        {
            Session.Clear();//remove session
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }
        //create a string MD5
        public static string GetMD5(string str)
        {
            MD5 md5 = new MD5CryptoServiceProvider();
            byte[] fromData = Encoding.UTF8.GetBytes(str);
            byte[] targetData = md5.ComputeHash(fromData);
            string byte2String = null;

            for (int i = 0; i < targetData.Length; i++)
            {
                byte2String += targetData[i].ToString("x2");

            }
            return byte2String;
        }
        public ActionResult QuenMK()
        {
            return View();
        }

        public JsonResult CheckEmailAvailability(string email)
        {
            System.Threading.Thread.Sleep(200);

            var mailCus = database.DaiLies.Where(x => x.Email == email).SingleOrDefault();
            if (mailCus != null)
            {
                return Json(1);
            }
            else
            {
                return Json(0);
            }
        }

        public JsonResult CheckNoPhoneAvailability(string noPhone)
        {
            System.Threading.Thread.Sleep(200);

            var noPhoneCus = database.DaiLies.Where(x => x.SDT == noPhone).SingleOrDefault();
            if (noPhoneCus != null)
            {
                return Json(1);
            }
            else
            {
                return Json(0);
            }
        }

        public JsonResult CheckUserNameAvailability(string userName)
        {
            System.Threading.Thread.Sleep(200);

            var userNameCus = database.DaiLies.Where(x => x.UserName == userName).SingleOrDefault();
            if (userNameCus != null)
            {
                return Json(1);
            }
            else
            {
                return Json(0);
            }
        }

        public ActionResult DangKy()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DangKy(DaiLy daiLy, string ConfirmPassword)
        {
            Random random = new Random();

            var sdt = database.DaiLies.Count(s => s.SDT == daiLy.SDT);
            var email = database.DaiLies.Count(s => s.Email == daiLy.Email);
            var username = database.DaiLies.Count(s => s.UserName == daiLy.UserName);

            if ((sdt >= 1) || (email >= 1) || (username >= 1))
            {
                TempData["errorInfo"] = "Thông tin đã bị trùng";
                return View(daiLy);
            }

            if (daiLy.Password.Length < 6)
            {
                TempData["errorPass"] = "Mật khẩu tổi thiểu 6 ký tự";
                return View(daiLy);
            }
            if (ModelState.IsValid)
            {
                if (ConfirmPassword != daiLy.Password)
                {
                    TempData["errorMK"] = "Xác thực mật khẩu không chính xác";
                    return View(daiLy);
                }
                else if (ConfirmPassword == daiLy.Password)
                {
                    var maDL = "DL" + random.Next(0, 9) + random.Next(0, 9) + random.Next(0, 9) + random.Next(0, 9);
                    daiLy.MaDL = maDL;
                    daiLy.MaLoaiDL = "LDL03";
                    daiLy.NgayTao = System.DateTime.Now;
                    database.DaiLies.Add(daiLy);
                    database.SaveChanges();
                    TempData["success"] = "Đăng kí thành công";
                    return RedirectToAction("Login");
                }
            }
            return RedirectToAction("DangKy");
        }
    }
}

Test02/Views/LoginDL/DangKy.cshtml
@model Test02.Models.DaiLy
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>DangKy</title>

    <meta name="viewport" content="width=device-width" />
    <title>Trang đăng nhập</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="~/Content/vendor/bootstrap/css/bootstrap.min.css">
    @*<link rel="stylesheet" type="text/css" href="~/Content/fonts/font-awesome-4.7.0/css/font-awesome.min.css">*@
    @*<link rel="stylesheet" type="text/css" href="~/Content/vendor/animate/animate.css">*@
    @*<link rel="stylesheet" type="text/css" href="~/Content/vendor/css-hamburgers/hamburgers.min.css">*@
    @*<link rel="stylesheet" type="text/css" href="~/Content/vendor/select2/select2.min.css">*@
    <link rel="stylesheet" type="text/css" href="~/Content/css/util.css">
    <link href="~/Content/Test01/mainDKyDL.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-5.0.2-dist/css/bootstrap.min.css" rel="stylesheet" />
    @*<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">*@
    @*<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-sweetalert/1.0.1/sweetalert.min.css">*@
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"></script>
    @*<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">*@
    @*<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">*@
    @*<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">*@
    <link rel="stylesheet" href="https://unpkg.com/boxicons@latest/css/boxicons.min.css">
</head>

<body>
    @if (TempData["errorInfo"] != null)
    {
        <script>
            swal({
                title: "Thông tin đã bị trùng",
                icon: "warning",
                button: "Thoát",
            });
        </script>
    }

    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100" @*style="background-image: url('../../Content/images/backgroungteam.png');"*@ />
            <div class="row" style="text-align: center; margin-top: 20px;">
                <h4>ĐĂNG KÝ ĐẠI LÝ</h4>
            </div>

            @using (Html.BeginForm("DangKy", "LoginDL", FormMethod.Post))
            {
                <div class="row" style="padding: 20px; font-size: 18px;">
                    <div class="col-md-6" style="border-right: 2px solid #FFD43B;">
                        <div class="col-md-12" style="padding:0px 40px 0px 40px;">
                            <div class="form-group">
                                <h6>Thông tin đại lý</h6>
                            </div>
                            <div class="form-group">
                                <label class="">Tên đại lý *</label>
                                @Html.EditorFor(model => model.TenDL, new { htmlAttributes = new { @class = "form-control col-md-12", required = "required", @placeholder = "Tên đại lý" } })
                                @Html.ValidationMessageFor(model => model.TenDL, "", new { @class = "text-danger", })@*<input class="form-control col-md-12" type="text" placeholder="Tên đại lý" name="">*@
                            </div>
                            <div class="form-group">
                                <label>Số điện thoại *</label>
                                @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control col-md-12", required = "required", @placeholder = "Số điện thoại", @id = "NoPhone", onchange = "NoPhoneCheck()" } })
                                @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger", })
                                <span id="noti"></span>@*<input class="form-control col-md-12" type="text" placeholder="Số điện thoại">*@
                            </div>
                            <div class="form-group">
                                <label>Địa chỉ *</label>
                                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control col-md-12", required = "required", @placeholder = "Địa chỉ" } })
                                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger", })
                            </div>
                            <div class="form-group">
                                <label>Email *</label>
                                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control col-md-12", @placeholder = "Email", required = "required", @id = "Email", onchange = "EmailCheck()" } })
                                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger", })
                                <span id="mess"></span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="col-md-12" style="padding:0px 40px 0px 40px;">
                            <div class="form-group">
                                <h6>Thông tin đăng nhập</h6>
                            </div>
                            <div class="form-group">
                                <label>Tên đăng nhập *</label>
                                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control col-md-12", required = "required", @placeholder = "Tên đăng nhập", @id = "UserName", onchange = "UserNameCheck()" } })
                                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger", })
                                <span id="status"></span>
                            </div>
                            <div class="form-group">
                                <label>Mật khẩu *</label>
                                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control col-md-12", @placeholder = "Mật khẩu", @type = "password" } })
                                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger", })
                                <span toggle="#password-field" id="spanElement" class="bx fa-fw bx-hide field-icon click-eye"></span>
                                <span class="focus-input100"></span>
                                @if (TempData["errorPass"] != null)
                                {
                                    <p style="color: red;">
                                        @TempData["errorPass"]
                                    </p>
                                }
                                @*<input class="form-control col-md-12" type="password" />*@
                            </div>
                            <div class="form-group">
                                <label>Nhập lại mật khẩu *</label>
                                <input class="form-control col-md-12 text-box single-line" type="password" name="ConfirmPassword" placeholder="Xác thực mật khẩu" />
                                @if (TempData["errorMK"] != null)
                                {
                                    <p style="color: red;">
                                        @TempData["errorMK"]
                                    </p>
                                }
                            </div>
                            <div class="form-group">
                                <div style="text-align: center; margin-top: 10px;">
                                    <a class="btn btn-danger btn-sm" href="/LoginDL/Login">Đăng nhập</a>
                                    <input class="btn btn-success btn-sm" type="submit" value="Đăng ký" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</body>
</html>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script src="Scripts/jquery-1.4.1.js" type="text/javascript"></script>
<script type="text/javascript">
        function EmailCheck() {
            $("#mess").html("check ...");
            $.post("@Url.Action("CheckEmailAvailability", "LoginDL")",
                {
                    email: $("#Email").val()
                },
                function (data) {
                    if (data == 0) {
                        $("#mess").html('<font color="Green">Available!</font>');
                        $("#Email").css("border-color", "Green");
                    }
                    else {
                        $("#mess").html('<font color="Red">Email này đã tồn tại</font>');
                        $("#Email").css("border-color", "Red");
                    }
                }
            )
        }

        function NoPhoneCheck() {
            $("#noti").html("check ...");
            $.post("@Url.Action("CheckNoPhoneAvailability", "LoginDL")",
                {
                    noPhone: $("#NoPhone").val()
                },
                function (data) {
                    if (data == 0) {
                        $("#noti").html('<font color="Green">Available!</font>');
                        $("#NoPhone").css("border-color", "Green");
                    }
                    else {
                        $("#noti").html('<font color="Red">Số điện thoại đã tồn tại</font>');
                        $("#NoPhone").css("border-color", "Red");
                    }
                }
            )
        }

        function UserNameCheck() {
            $("#status").html("check ...");
            $.post("@Url.Action("CheckUserNameAvailability", "LoginDL")",
                {
                    userName: $("#UserName").val()
                },
                function (data) {
                    if (data == 0) {
                        $("#status").html('<font color="Green">Available!</font>');
                        $("#UserName").css("border-color", "Green");
                    }
                    else {
                        $("#status").html('<font color="Red">Tên đăng nhập đã tồn tại</font>');
                        $("#UserName").css("border-color", "Red");
                    }
                }
            )
        }
</script>

<!--Javascript-->
<script src="~/Content/js/main.js"></script>
@*<script src="https://unpkg.com/boxicons@latest/dist/boxicons.js"></script>*@
@*<script src="~/Content/vendor/jquery/jquery-3.2.1.min.js"></script>*@
@*<script src="~/Content/vendor/bootstrap/js/popper.js"></script*@>
@*<script src="~/Content/vendor/bootstrap/js/bootstrap.min.js"></script>*@
@*<script src="~/Content/vendor/select2/select2.min.js"></script>*@
<script type="text/javascript">
    //show - hide mật khẩu
    function myFunction() {
        var x = document.getElementById("myInput");
        if (x.type === "password") {
            x.type = "text"
        } else {
            x.type = "password";
        }
    }
    $(".click-eye").click(function () {
        $(this).toggleClass("bx-show bx-hide");
        var input = $($(this).attr("toggle"));
        if (input.attr("type") == "password") {
            input.attr("type", "text");
        } else {
            input.attr("type", "password");
        }
    });
    const ipnElement = document.querySelector('#Password')
    const spanElement = document.querySelector('#spanElement')
    // step 2
    spanElement.addEventListener('click', function () {
        // step 3
        const currentType = ipnElement.getAttribute('type')
        // step 4
        ipnElement.setAttribute(
            'type',
            currentType === 'password' ? 'text' : 'password'
        )
    })
</script>

Test02/Views/LoginDL/Login.cshtml
@model Test02.Models.DaiLy
@{
    Layout = null;
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Trang đăng nhập</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="~/Content/vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="~/Content/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="~/Content/vendor/animate/animate.css">
    <link rel="stylesheet" type="text/css" href="~/Content/vendor/css-hamburgers/hamburgers.min.css">
    <link rel="stylesheet" type="text/css" href="~/Content/vendor/select2/select2.min.css">
    <link rel="stylesheet" type="text/css" href="~/Content/css/util.css">
    <link rel="stylesheet" type="text/css" href="~/Content/css/main.css">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-sweetalert/1.0.1/sweetalert.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">
    <link rel="stylesheet" href="https://unpkg.com/boxicons@latest/css/boxicons.min.css">
</head>
<body>
    @if (TempData["success"] != null)
    {
        <script>
            swal({
                title: "Bạn đã đăng kí thành công",
                icon: "success",
                button: "Thoát",
            });
        </script>
    }

    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100">
                <div class="login100-pic js-tilt" data-tilt>
                    <img src="~/Content/images/backgroungteam.png" alt="IMG">
                </div>
                <!--=====TIÊU ĐỀ======-->
                @using (Html.BeginForm("Login", "LoginDL", FormMethod.Post))
                {

                    <span class="login100-form-title">
                        <b>ĐẠI LÝ ĐĂNG NHẬP</b>
                    </span>
                    <!--=====FORM INPUT TÀI KHOẢN VÀ PASSWORD======-->
                    <div class="wrap-input100 validate-input">
                        <input class="input100" type="text" placeholder="Tài khoản đại lý" name="UserName"
                               id="UserName">
                        <span class="focus-input100"></span>
                        <span class="symbol-input100">
                            <i class='bx bx-user'></i>
                        </span>
                    </div>
                    <div class="wrap-input100 validate-input">
                        <input autocomplete="off" class="input100" type="password" placeholder="Mật khẩu"
                               name="Password" id="Password">
                        <span toggle="#password-field" id="spanElement" class="bx fa-fw bx-hide field-icon click-eye"></span>
                        <span class="focus-input100"></span>
                        <span class="symbol-input100">
                            <i class='bx bx-key'></i>
                        </span>
                    </div>
                    <p class="text-danger">@TempData["error"]</p>
                    <!--=====ĐĂNG NHẬP======-->
                    <div class="container-login100-form-btn">
                        <input type="submit" value="Đăng nhập" />
                    </div>
                    <!--=====LINK TÌM MẬT KHẨU======-->
                    <div class="text-right p-t-12">
                        @*<a class="txt2" href="~/LoginDL/QuenMK">
                            Bạn quên mật khẩu?
                        </a>*@
                        <a class="txt2" href="~/LoginDL/DangKy" @*style="margin-left: 90px;"*@>
                            Đăng ký
                        </a>
                    </div>
                }
                <!--=====FOOTER======-->
                <div class="text-center p-t-70 txt2">
                    Phần mềm quản lý đại lý <i class="far fa-copyright" aria-hidden="true"></i>
                    <script type="text/javascript">document.write(new Date().getFullYear());</script> <a class="txt2" href="https://www.facebook.com/nha.truong.3110567/"> Code bởi nhỏm G02_Quản Lý các đại lý (CNPM_Huflit) </a>
                </div>
            </div>
        </div>
    </div>
    <!--Javascript-->
    <script src="~/Content/js/main.js"></script>
    <script src="https://unpkg.com/boxicons@latest/dist/boxicons.js"></script>
    <script src="~/Content/vendor/jquery/jquery-3.2.1.min.js"></script>
    <script src="~/Content/vendor/bootstrap/js/popper.js"></script>
    <script src="~/Content/vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/Content/vendor/select2/select2.min.js"></script>
    <script type="text/javascript">
        //show - hide mật khẩu
        function myFunction() {
            var x = document.getElementById("myInput");
            if (x.type === "password") {
                x.type = "text"
            } else {
                x.type = "password";
            }
        }
        $(".click-eye").click(function () {
            $(this).toggleClass("bx-show bx-hide");
            var input = $($(this).attr("toggle"));
            if (input.attr("type") == "password") {
                input.attr("type", "text");
            } else {
                input.attr("type", "password");
            }
        });
        const ipnElement = document.querySelector('#Password')
        const spanElement = document.querySelector('#spanElement')
        // step 2
        spanElement.addEventListener('click', function () {
            // step 3
            const currentType = ipnElement.getAttribute('type')
            // step 4
            ipnElement.setAttribute(
                'type',
                currentType === 'password' ? 'text' : 'password'
            )
        })
    </script>

</body>
</html>

Test02/Views/LoginDL/QuenMK.cshtml
@{
    ViewBag.Title = "QuenMK";
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>@ViewBag.Title</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="~/Content/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="~/Content/bootstrap-icons/fonts/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="~/Content/Test01/animate.css">
    <link rel="stylesheet" type="text/css" href="~/Content/Test01/hamburgers.min.css">
    <link rel="stylesheet" type="text/css" href="~/Content/Test01/select2.min.css">
    <link rel="stylesheet" type="text/css" href="~/Content/Test01/util.css">
    <link rel="stylesheet" type="text/css" href="~/Content/Test01/mainLogin.css">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-sweetalert/1.0.1/sweetalert.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">
    <link rel="stylesheet" href="https://unpkg.com/boxicons@latest/css/boxicons.min.css">
</head>

<body>
    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100">
                <div class="login100-pic js-tilt" data-tilt>
                    <img src="~/Content/images/fg-img.png" alt="IMG">
                </div>
                <form class="login100-form validate-form">
                    <span class="login100-form-title">
                        <b>KHÔI PHỤC MẬT KHẨU</b>
                    </span>
                    <form action="custommer.html">
                        <div class="wrap-input100 validate-input"
                             data-validate="Bạn cần nhập đúng thông tin như: ex@abc.xyz">
                            <input class="input100" type="text" placeholder="Nhập email" name="emailInput"
                                   id="emailInput" value="" />
                            <span class="focus-input100"></span>
                            <span class="symbol-input100">
                                <i class='bx bx-mail-send'></i>
                            </span>
                        </div>
                        <div class="container-login100-form-btn">
                            <input type="button" onclick="return RegexEmail('emailInput')" value="Lấy mật khẩu" />
                        </div>

                        <div class="text-center p-t-12">
                            <a class="txt2" href="~/LoginDL/Login">
                                Trở về đăng nhập
                            </a>
                        </div>
                    </form>
                    <div class="text-center p-t-70 txt2">
                        Phần mềm quản lý các đại lý <i class="far fa-copyright" aria-hidden="true"></i>
                        <script type="text/javascript">document.write(new Date().getFullYear());</script>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div>
        @RenderBody()
    </div>
    <!--===============================================================================================-->
    <!--===============================================================================================-->
    <script src="~/Scripts/jquery-3.2.1.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/Content/js/popper.js"></script>
    <!--===============================================================================================-->
    <script src="~/Content/js/bootstrap.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/Content/Test01/select2.min.js"></script>
    <!--===============================================================================================-->

</body>
</html>