Test02/Models/BaoCao.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoCao
    {
        public string MaBC { get; set; }
        public string MaNV { get; set; }
        public string LoaiBC { get; set; }
        public Nullable<System.DateTime> NgayLapBC { get; set; }
        public string NoiDungBC { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}

Test02/Controllers/KinhDoanhController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Test02.Models;
using Test02.App_Start;
using System.Data;
using System.Net;
using System.IO;
using System.Web.Helpers;

namespace Test02.Controllers
{
    [Authentication (MaChucVu ="NVKD")]
    public class KinhDoanhController : Controller
    {

        QuanLyDLproEntities2 database = new QuanLyDLproEntities2();
        // GET: KinhDoanh
        public ActionResult TrangChu()
        {
            return View();
        }

        public ActionResult QuanLyDL()
        {
            return View(database.DaiLies.ToList().OrderByDescending(s=> s.NgayTao));
        }
        //Kiểm tra tên đại lý
        [HttpPost]
        public ActionResult KTTenDL(string TenDL)
        {
            var check = database.DaiLies.Where(s => s.TenDL == TenDL).FirstOrDefault();
            if(check != null)
            {
                return Json(new { success = false}, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }
        }
        [HttpPost]
        public ActionResult KTSDT(string SDT)
        {
            var check = database.DaiLies.Where(s => s.SDT == SDT).FirstOrDefault();
            if (check != null)
            {
                return Json(new { success = false }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }
        }
        [HttpPost]
        public ActionResult KTEmail(string Email)
        {
            if (Email.IndexOf("@gmail.com") > 0)
            {
                var check = database.DaiLies.Where(s => s.Email == Email).FirstOrDefault();
                if (check != null)
                {
                    return Json(new { success = false }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { success = true }, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                return Json(new { success = false }, JsonRequestBehavior.AllowGet);
            }
            
        }
        public ActionResult ThemDL()
        {
            ViewBag.MaLoaiDL = new SelectList(database.LoaiDLs, "MaLoaiDL", "TenDaiLy");
            return View();
        }

        public ActionResult ChinhSuaDL(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            DaiLy daiLy = database.DaiLies.Find(id);
            if (daiLy == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaLoaiDL = new SelectList(database.LoaiDLs, "MaLoaiDL", "TenDaiLy", daiLy.MaLoaiDL);
            return View(daiLy);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ChinhSuaDL([Bind(Include = "MaDL,MaLoaiDL,UserName,Password,TenDL,SDT,DiaChi,Email,NgayTao")] DaiLy daiLy)
        {
            if (ModelState.IsValid)
            {
                database.Entry(daiLy).State = System.Data.Entity.EntityState.Modified;
                database.SaveChanges();
                return RedirectToAction("QuanLyDL");
            }
            ViewBag.MaLoaiDL = new SelectList(database.LoaiDLs, "MaLoaiDL", "TenDaiLy", daiLy.MaLoaiDL);
            return View(daiLy);
        }
        [HttpPost]
        public ActionResult ResetPass(string madl)
        {
            if (madl == null)
            {
                return Json(new { success = false }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var resetpass = database.DaiLies.Find(madl);
                resetpass.Password = "123456";
                database.Entry(resetpass).State = System.Data.Entity.EntityState.Modified;
                database.SaveChanges();
                TempData["madl"] = madl;
                //Gửi emil về tk
                var daily = database.DaiLies.Find(madl);
                string content = System.IO.File.ReadAllText(Server.MapPath("~/TemplateMail/ResetPasss.html"));
                content = content.Replace("{{TenDL}}", daily.Email);
                content = content.Replace("{{username}}", daily.UserName);
                content = content.Replace("{{time}}", DateTime.Now.ToString());
                //content = content.Replace("{{Total}}", tongtien);
                //content = content.Replace("{{Thoigian}}", Convert.ToString(ttkh.CreateDate));
                //content = content.Replace("{{Invoice}}", themhd.MaHD);
                string subject = "Tài khoản đại lý "+daily.MaDL+" của bạn vừa được cập nhật !";
                WebMail.Send(daily.Email, subject, content, null, null, null, true, null, null, null, null, null, null);
                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }
            
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ThemDL([Bind(Include = "MaLoaiDL,UserName,Password,TenDL,SDT,DiaChi,Email")] DaiLy daiLy)
        {
            if (ModelState.IsValid)
            {
                Random rd = new Random();
                var madl = "DL" + rd.Next(0, 10) + rd.Next(0, 10) + rd.Next(0, 10) + rd.Next(0, 10);
                daiLy.MaDL = madl;
                daiLy.NgayTao = System.DateTime.Now;
                daiLy.Password = "123456";
                database.DaiLies.Add(daiLy);
                database.SaveChanges();
                TempData["messageAlert"] = "Đã thêm mới";
                TempData["TenDLthem"] = daiLy.TenDL;
                //Gửi emil về tk
                string content = System.IO.File.ReadAllText(Server.MapPath("~/TemplateMail/AddAccount.html"));
                content = content.Replace("{{email}}", daiLy.Email);
                content = content.Replace("{{Password}}", daiLy.Password);
                content = content.Replace("{{tentk}}", daiLy.TenDL);
                //content = content.Replace("{{Total}}", tongtien);
                //content = content.Replace("{{Thoigian}}", Convert.ToString(ttkh.CreateDate));
                //content = content.Replace("{{Invoice}}", themhd.MaHD);
                string subject = "Đây là tin nhắn tự động từ hệ thống POS";
                WebMail.Send(daiLy.Email, subject, content, null, null, null, true, null, null, null, null, null, null);
                return RedirectToAction("QuanLyDL");
            }
            
            ViewBag.MaLoaiDL = new SelectList(database.LoaiDLs, "MaLoaiDL", "TenDaiLy", daiLy.MaLoaiDL);
            return View(daiLy);
        }
        // GET: DaiLies/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            DaiLy daiLy = database.DaiLies.Find(id);
            if (daiLy == null)
            {
                return HttpNotFound();
            }
            return View(daiLy);
        }

        // POST: DaiLies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            DaiLy daiLy = database.DaiLies.Find(id);
            database.DaiLies.Remove(daiLy);
            database.SaveChanges();
            //Gửi emil về tk
            string content = System.IO.File.ReadAllText(Server.MapPath("~/TemplateMail/DeleteAccount.html"));
            content = content.Replace("{{TenDL}}", daiLy.TenDL);
            content = content.Replace("{{username}}", daiLy.UserName);
            content = content.Replace("{{time}}", DateTime.Now.ToString());
            //content = content.Replace("{{Total}}", tongtien);
            //content = content.Replace("{{Thoigian}}", Convert.ToString(ttkh.CreateDate));
            //content = content.Replace("{{Invoice}}", themhd.MaHD);
            string subject = "BẠN ĐÃ XÓA TÀI KHOẢN ĐẠI LÝ";
            WebMail.Send(daiLy.Email, subject, content, null, null, null, true, null, null, null, null, null, null);
            return RedirectToAction("QuanLyDL");
        }
        //Quản lý đơn hàng
        public ActionResult QuanLyDH()
        {
            return View(database.DonHangs.ToList().OrderBy(s => s.NgayLap));
        }
        [HttpPost]
        public ActionResult CheckCongNoDL(string MaDL, string ThanhTien)
        {
            var tongtiendh = 0;
            var daily = database.DaiLies.Where(s => s.MaDL == MaDL).FirstOrDefault();
            tongtiendh += Convert.ToInt32(ThanhTien);
            if (daily.MaLoaiDL == "LDL01" && tongtiendh <= 500000000)
            {
                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }
            else if (daily.MaLoaiDL == "LDL02" && tongtiendh <= 250000000)
            {
                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }
            else if (daily.MaLoaiDL == "LDL03" && tongtiendh <= 100000000)
            {
                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { success = false }, JsonRequestBehavior.AllowGet);
            }
        }
        //Thêm mới đơn hàng
        public ActionResult ThemDH()
        {
            ViewBag.MaDL = new SelectList(database.DaiLies, "MaDL", "MaDL");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ThemDH([Bind(Include = "MaDH,MaDL,NgayLap,DiemGiao")] DonHang donHang)
        {
            DataTable dh = new DataTable();
            if (Session["DonHang"] == null)
            {

Test02/Controllers/TuChoiTruyCapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Test02.Controllers
{
    public class TuChoiTruyCapController : Controller
    {
        // GET: TuChoiTruyCap
        public ActionResult TuChoiTruyCap()
        {
            return View();
        }
    }
}

Test02/Views/KinhDoanh/ChinhSuaCTDH.cshtml
@model Test02.Models.ChiTietDonHang
@using Test02.Models;
@{
    ViewBag.Title = "ChinhSuaCTDH";
    Layout = "~/Views/KinhDoanh/Layout/LayoutKD.cshtml";
    ViewBag.dh = "active";
    ViewBag.nd = "Chỉnh sửa chi tiết đơn hàng";
    QuanLyDLproEntities2 db = new QuanLyDLproEntities2();
}

<div class="tile">
    @{var madl = db.DonHangs.Where(s => s.MaDH == Model.MaDH).FirstOrDefault();
    }
    <h2>Chỉnh sửa chi tiết đơn hàng @Model.MaDH của đại lý @madl.MaDL</h2>
    <div class="tile-body">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>ChiTietDonHang</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.MaCTDH)
                @Html.HiddenFor(model => model.MaDH)
                @Html.HiddenFor(model => model.ChietKhau)
                @Html.HiddenFor(model => model.ThanhTien)
                <div class="form-group">
                    @Html.LabelFor(model => model.MaSP, "MaSP", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @{ 
                            var dssp = db.SanPhams.ToList().OrderBy(s=>s.MaSP);
                            var tensp = db.SanPhams.Where(s => s.MaSP == Model.MaSP).FirstOrDefault();
                        }
                        <select class="form-control" id="MaSP" name="MaSP">
                            <option value="@Model.MaSP">@Model.MaSP -- @tensp.TenSP </option>
                            @{
                                foreach (var item01 in dssp)
                                {
                                    if (Model.MaSP != item01.MaSP) 
                                    { 
                                        <option value="@item01.MaSP">@item01.MaSP -- @item01.TenSP</option>
                                    }
                                    
                                }

                            }
                        </select>
                        @Html.ValidationMessageFor(model => model.MaSP, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.SoLuong, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.SoLuong, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SoLuong, "", new { @class = "text-danger" })
                    </div>
                </div>



                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Lưu chi tiết đơn hàng @Model.MaDH" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }
        <div>
            @Html.ActionLink("Quay lại danh sách đơn hàng", "QuanLyDH")
        </div>
    </div>
</div>

Test02/Views/KinhDoanh/ChinhSuaSP.cshtml
@model Test02.Models.SanPham

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/KinhDoanh/Layout/LayoutKD.cshtml";
    ViewBag.sp = "active";
    ViewBag.nd = "Chỉnh sửa sản phẩm";
    ViewBag.hieuung5 = "bx-tada";
}

<link href="~/Content/Test01/UploadAnh.css" rel="stylesheet" />
<div class="row">
    <div class="col-md-12">
        <div class="tile">
            <h3 class="tile-title">Chỉnh sửa sản phẩm @Model.MaSP</h3>
            <div class="tile-body mt-3">
                @using (Html.BeginForm("ChinhSuaSP", "KinhDoanh", FormMethod.Post, new { enctype = "multipart/form-data", @class = "row" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.MaSP)
                    @Html.HiddenFor(model => model.TongTon)
                    <div class="form-group col-md-5" style="border-right:5px solid red">
                        <label class="control-label">Ảnh sản phẩm</label>
                        <div id="myfileupload">
                            <input type="file" id="uploadfile" name="HinhAnh" value="@Model.HinhAnh" onchange="readURL(this);" />
                        </div>
                        <div id="thumbbox">
                            <img height="200" width="400" alt="Thumb image" id="thumbimage" src="@Model.HinhAnh" />
                            <a class="removeimg" href="javascript:"></a>
                        </div>
                        <div id="boxchoice">
                            <a href="javascript:" class="Choicefile"><i class="fas fa-cloud-upload-alt"></i> Chọn ảnh</a>
                            <p style="clear:both"></p>
                        </div>

                    </div>
                    <div class="form-group col-md-6">
                        <div class="row">
                            <div class="form-group col-md-5">
                                @Html.LabelFor(model => model.TenSP, htmlAttributes: new { @class = "control-label col-md-2" })
                                @Html.EditorFor(model => model.TenSP, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.TenSP, "", new { @class = "text-danger" })
                            </div>

                            <div class="form-group col-md-4">
                                <label class="control-label">Đơn vị tính</label>
                                <select class="form-control" name="DonViTinh" required>
                                    <option selected disabled value="@Model.DonViTinh">-----@Model.DonViTinh-----</option>
                                    <option value="Thùng_Lon">Thùng_Lon</option>
                                    <option value="Thùng_Chai">Thùng_Chai</option>
                                    <option value="Lốc">Lốc</option>
                                    <option value="Lon">Lon</option>
                                    <option value="Chai">Chai</option>
                                </select>
                                @Html.ValidationMessageFor(model => model.DonViTinh, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group col-md-3">
                                <label class="control-label">Giá sản phẩm</label>
                                @Html.EditorFor(model => model.Gia, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Gia, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group col-md-5">
                                <label class="control-label">Ngày sản xuất: </label>
                                <label class="">Ngày sản xuất cập nhật lần cuối : @Model.NgaySX</label>
                                <input class="form-control text-box single-line" data-val="true" data-val-date="The field NgayXuat must be a date." required id="NgaySX" name="NgaySX" type="date" value="">
                                @Html.ValidationMessageFor(model => model.NgaySX, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group col-md-5">
                                <label class="control-label">Hạn sử dụng:</label>
                                <label class="">Hạn sử dụng cập nhật lần cuối : @Model.HanSD</label>
                                <input class="form-control text-box single-line" data-val="true" data-val-date="The field HanSH must be a date." required id="HanSD" name="HanSD" type="Date" value="">
                                @Html.ValidationMessageFor(model => model.HanSD, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="form-group col-md-12 mt-3">
                        <a class="btn btn-outline-warning" href="~/KinhDoanh/QuanLySP">
                            Quay lại danh sách sản phẩm
                        </a>
                        <input type="submit" value="Lưu thông tin sản phẩm " class="btn btn-outline-success" />
                    </div>
                }
            </div>
        </div>
    </div>
</div>
@section script{
    <script>
        function readURL(input, thumbimage) {
            if (input.files && input.files[0]) { //Sử dụng  cho Firefox - chrome
                var reader = new FileReader();
                reader.onload = function (e) {
                    $("#thumbimage").attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
            else { // Sử dụng cho IE
                $("#thumbimage").attr('src', input.value);

            }
            $("#thumbimage").show();
            $('.filename').text($("#uploadfile").val());
            $('.Choicefile').css('background', '#14142B');
            $('.Choicefile').css('cursor', 'default');
            $(".removeimg").show();
            $(".Choicefile").unbind('click');

        }
        $(document).ready(function () {
            $(".Choicefile").bind('click', function () {
                $("#uploadfile").click();
            });
            $(".removeimg").click(function () {
               /* $("#thumbimage").attr('src', '').hide();*/
                $("#thumbimage").attr('src', '@Model.HinhAnh').show();
                $("#myfileupload").html('<input type="file" id="uploadfile" name="HinhAnh" value="@Model.HinhAnh" onchange="readURL(this);" />');
                $(".removeimg").hide();
                $(".Choicefile").bind('click', function () {
                    $("#uploadfile").click();
                });
                $('.Choicefile').css('background', '#14142B');
                $('.Choicefile').css('cursor', 'pointer');
                $(".filename").text("");
            });
            
        })
        $("#NgaySX").on('input', function () {
            var check = $("#NgaySX").val();
            console.log(check);
            $("#HanSD").attr("min", '' + check);
        });
    </script>
    
}

Test02/Views/KinhDoanh/ThemCTHD_1.cshtml
@model Test02.Models.ChiTietDonHang

@{
    ViewBag.Title = "ThemCTHD_1";
    Layout = "~/Views/KinhDoanh/Layout/LayoutKD.cshtml";
}

<h2>ThemCTHD_1</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ChiTietDonHang</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MaDH, "MaDH", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaDH", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaDH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaSP, "MaSP", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaSP", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaSP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoLuong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoLuong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoLuong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DonGia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DonGia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DonGia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ChietKhau, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ChietKhau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ChietKhau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ThanhTien, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ThanhTien, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ThanhTien, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiemGiao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiemGiao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiemGiao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DonViTinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DonViTinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DonViTinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


@*<div class="tile">
    <h3 class="tile-title">Nhập chi tiết đơn hàng </h3>
    <div class="tile-body">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Tạo đơn hàng</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.MaCTDH)
                @Html.HiddenFor(model => model.MaDH)
                <div class="form-group">
                    @Html.LabelFor(model => model.MaSP, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.DropDownList("MaSP", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.MaSP, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.SoLuong, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.SoLuong, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SoLuong, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.DonGia, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.DonGia, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DonGia, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.DonViTinh, htmlAttributes: new { @class = "control-label col-md-2" })
                    <select class="form-control" id="DonViTinh" name="DonViTinh">
                        <option value="Thùng">Thùng</option>
                        <option value="Lon">Lon</option>
                        <option value="Chai">Chai</option>
                        <option value="Lốc (6 lon)">Lốc (6 lon)</option>
                        <option value="Lốc (6 chai)">Lốc (6 chai)</option>
                    </select>
                    @Html.ValidationMessageFor(model => model.DonViTinh, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Thêm đơn hàng" class="btn btn-default" /> ||
                    <a class="btn btn-success" href="@Url.Action("DatThemCTDH", "KinhDoanh", new {ChiTietDH = Model.MaDH})"> Đặt thêm sản phẩm</a>
                </div>
            </div>
        }
    </div>
</div>

<div>
    @Html.ActionLink("Quay lại danh sách đơn hàng", "QuanLyDH")
</div>*@

Test02/Views/KinhDoanh/ThemDH.cshtml
@model Test02.Models.DonHang

@{
    ViewBag.Title = "ThemDH";
    Layout = "~/Views/KinhDoanh/Layout/LayoutKD.cshtml";
    ViewBag.dh = "active";
    ViewBag.nd = "Thêm mới đơn hàng";
}

<div class="tile">
    <h3 class="tile-title">Thêm mới đơn hàng cho đại lý</h3>
    <div class="tile-body">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Tạo đơn hàng</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.MaDH)
                @Html.HiddenFor(model => model.MaNVLap)
                <div class="form-group">
                    @Html.LabelFor(model => model.MaDL, "MaDL", htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.DropDownList("MaDL", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.MaDL, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.DiemGiao, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.DiemGiao, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DiemGiao, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Thêm đơn hàng" class="btn btn-default" />
                    </div>
                    <div class="btn btn-close">
                        @Html.ActionLink("Quay lại danh sách đơn hàng", "QuanLyDH")
                    </div>

                </div>
            </div>
        }
    </div>
</div>

Test02/Views/KinhDoanh/TuChoiTruyCap.cshtml
@{
    ViewBag.Title = "TuChoiTruyCap";
    Layout = "~/Views/KinhDoanh/Layout/LayoutKD.cshtml";
}

<h2>Từ chối truy cập </h2>