Test02/Controllers/KeToanController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.Routing;
using Test02.App_Start;
using Test02.Models;



namespace Test02.Controllers
{
    [Authentication(MaChucVu = "NVKT")]
    public class KeToanController : Controller
    {
        QuanLyDLproEntities2 database = new QuanLyDLproEntities2();
        // GET: KeToan
        public ActionResult Index()
        {
            return View();
        }

        public double maxno(string maloai)
        {
            double maxcn = 0;
            if (maloai == "LDL01")
            {
                maxcn = 500000000;
            }
            else if (maloai == "LDL02")
            {
                maxcn = 250000000;
            }
            else
            {
                maxcn = 100000000;
            }
            return maxcn;
        }
        public int SoTinhTrangDaiLy()
        {
            int countdl = 0;
            List<DaiLy> dly = database.DaiLies.ToList();
            foreach (var item in dly)
            {
                double? a = database.sp_SumCN(item.MaDL).FirstOrDefault();
                double maxcndl = maxno(item.MaLoaiDL);
                double dangercn = maxcndl - (maxcndl * 0.2);
                if (a >= dangercn)
                {
                    countdl++;
                }
            }
            return countdl;
        }





        public ActionResult TrangChuKeToan()
        {

            ViewBag.tongdathanhtoan = database.sp_DHtheotinhtrang("Đã thanh toán").FirstOrDefault();
            ViewBag.tongchuathanhtoan = database.sp_DHtheotinhtrang("Chưa thanh toán").FirstOrDefault();
            ViewBag.tongdonno = database.sp_DHtheotinhtrang("Đang nợ").FirstOrDefault();
            ViewBag.donthanhtoan = database.sp_DonHangtrongngay("Đã thanh toán").FirstOrDefault();
            ViewBag.donchuathanhtoan = database.sp_DonHangtrongngay("Chưa thanh toán").FirstOrDefault();
            ViewBag.donno = database.sp_DonHangtrongngay("Đang nợ").FirstOrDefault();

            int dem = SoTinhTrangDaiLy();
            Session["demdl"] = dem;
            Session["doanhthu"] = database.sp_DoanhThutrongthang().FirstOrDefault();
            List<sp_CongNoDenHan_Result> cnhan = database.sp_CongNoDenHan().ToList();
            Session["cndenhan"] = cnhan;
            return View();
        }



        public List<DonHang> LocDonHang_TheoDK(string thang_chon, List<DonHang> tatcadonhang, string ttrang)
        {

            List<DonHang> dh = new List<DonHang>();
            if (thang_chon != "0")
            {
                foreach (var locdh in tatcadonhang)
                {
                    DateTime day = (DateTime)locdh.NgayLap;
                    var m = Convert.ToString(day.Month);

                    if (thang_chon == m && locdh.TinhTrangThanhToan == ttrang)
                    {
                        dh.Add(locdh);
                    }
                }
            }
            else
            {
                foreach (var locdh in tatcadonhang)
                {
                    if (locdh.TinhTrangThanhToan == ttrang)
                    {
                        dh.Add(locdh);
                    }
                }

            }
            return dh;

        }
        public List<DonHang> LayDonHang_TheoThang(string thang_chon, List<DonHang> tatcadonhang)
        {

            List<DonHang> dh = new List<DonHang>();
            if (thang_chon != "0")
            {
                foreach (var locdh in tatcadonhang)
                {
                    DateTime day = (DateTime)locdh.NgayLap;
                    var m = Convert.ToString(day.Month);

                    if (thang_chon == m)
                    {
                        dh.Add(locdh);
                    }
                }
            }
            else
            {
                dh = tatcadonhang;
            }
            return dh;

        }
        private void BindDropDownList()
        {
            List<SelectListItem> m = new List<SelectListItem>();
            m.Add(new SelectListItem { Text = "All", Value = "All" });
            m.Add(new SelectListItem { Text = "1", Value = "1" });
            m.Add(new SelectListItem { Text = "2", Value = "2" });
            m.Add(new SelectListItem { Text = "3", Value = "3" });
            m.Add(new SelectListItem { Text = "4", Value = "4" });
            m.Add(new SelectListItem { Text = "5", Value = "5" });
            m.Add(new SelectListItem { Text = "6", Value = "6" });
            m.Add(new SelectListItem { Text = "7", Value = "7" });
            m.Add(new SelectListItem { Text = "8", Value = "8" });
            m.Add(new SelectListItem { Text = "9", Value = "9" });
            m.Add(new SelectListItem { Text = "10", Value = "10" });
            m.Add(new SelectListItem { Text = "11", Value = "11" });
            m.Add(new SelectListItem { Text = "12", Value = "12" });
            TempData["thangs"] = m;
        }
        private void Tinhtangdonhang()
        {
            List<SelectListItem> tinhtrang = new List<SelectListItem>();
            tinhtrang.Add(new SelectListItem { Text = "All", Value = "All" });
            tinhtrang.Add(new SelectListItem { Text = "Chưa thanh toán", Value = "Chưa thanh toán" });
            tinhtrang.Add(new SelectListItem { Text = "Đang nợ", Value = "Đang nợ" });
            tinhtrang.Add(new SelectListItem { Text = "Đã thanh toán", Value = "Đã thanh toán" });
            TempData["tinhtrangdh"] = tinhtrang;
        }
        public ActionResult QLDonHang()
        {
            BindDropDownList();
            Tinhtangdonhang();
            List<sp_LocDonHang_Result> dh = database.sp_LocDonHang("All", "All", "Đã xét duyệt").ToList();
            return View(dh);
        }
        [HttpPost]
        public ActionResult QLDonHang(string thangs, string tinhtrangdh)
        {
            BindDropDownList();
            Tinhtangdonhang();
            List<sp_LocDonHang_Result> dh = database.sp_LocDonHang(thangs, tinhtrangdh, "Đã xét duyệt").ToList();
            return View(dh);
        }

        //public ActionResult QLDonChoGiao()
        //{
        //    BindDropDownList();
        //    Tinhtangdonhang();
        //    List<DonHang> donhangchuathanhtoan = database.DonHangs.Where(s => s.TrangThai == "Đã xét duyệt"
        //    && s.TinhTrangThanhToan == "Chưa thanh toán" && s.TinhTrangGH == "Chờ giao").ToList();

        //    return View(donhangchuathanhtoan);
        //}
        //[HttpPost]
        //public ActionResult QLDonChoGiao(string thangs, string tinhtrangdh)
        //{

        //    BindDropDownList();
        //    Tinhtangdonhang();
        //    List<DonHang> tatca = database.DonHangs.Where(s => s.TrangThai == "Đã xét duyệt" 
        //   && s.TinhTrangGH == "Chờ giao").ToList();
        //    List<DonHang> dhchon = LocDonHang_TheoDK(thangs, tatca, tinhtrangdh).ToList();
        //    return View(dhchon);
        //}

        //public ActionResult QLDonDaGiao()
        //{
        //    BindDropDownList();
        //    Tinhtangdonhang();
        //    List<DonHang> donhangchuathanhtoan = database.DonHangs.Where(s => s.TrangThai == "Đã xét duyệt"
        //    && s.TinhTrangThanhToan == "Chưa thanh toán" && s.TinhTrangGH == "Đã giao").ToList();

        //    return View(donhangchuathanhtoan);
        //}
        //[HttpPost]
        //public ActionResult QLDonDaGiao(string thangs, string tinhtrangdh)
        //{

        //    BindDropDownList();
        //    Tinhtangdonhang();
        //    List<DonHang> tatca = database.DonHangs.Where(s => s.TrangThai == "Đã xét duyệt"
        //   && s.TinhTrangGH=="Đã giao").ToList();
        //    List<DonHang> dhchon = LocDonHang_TheoDK(thangs, tatca, tinhtrangdh).ToList();
        //    return View(dhchon);
        //}


        //public ActionResult ChinhsuaHD(string id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
        //    }
        //    DonHang donHang = database.DonHangs.Find(id);
        //    if (donHang == null)
        //    {
        //        return HttpNotFound();
        //    }

        //    return View(donHang);
        //}





        public ActionResult XuatHDBH(String id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            DonHang donHang = database.DonHangs.Find(id);
            Session["madaily"] = id;
            if (donHang == null)
            {
                return HttpNotFound();
            }
            return View(donHang);
        }

        public ActionResult ChinhsuaHD(DonHang donHang)
        {
            if (ModelState.IsValid)
            {
                database.Entry(donHang).State = System.Data.Entity.EntityState.Modified;
                database.SaveChanges();
                TempData["edithd"] = "oke";
                return RedirectToAction("XuatHDBH/" + donHang.MaDH);
            }

            return View(donHang);
        }



        //private double TinhTongDonHang(List<DonHang> donhang)
        //{
        //    double tinhtongdh = 0;
        //    //= database.DonHangs.Where(s => s.MaDL == madl && s.TinhTrangThanhToan == "Chưa thanh toán" && s.TrangThai == "Đã xét duyệt").ToList();
        //    if (donhang != null)
        //    {
        //        foreach (var item in donhang)
        //        {
        //            tinhtongdh += (double)item.TongTien;

        //        }
        //    }
        //    return tinhtongdh;

        //}
        public List<DonHang> Get_DonHang(string thangs, string thanhtoan, string trangthai)
        {
            var dh = database.sp_LocDonHang(thangs, thanhtoan, trangthai).ToList();

Test02/Views/KeToan/DSCongnoNo.cshtml
@model IEnumerable<Test02.Models.PhieuCongNo>

@using Test02.Models;
@{
    ViewBag.Title = "Công nợ đại lý";
    Layout = "~/Views/KeToan/Layout/_LayoutPageKeToan.cshtml";
    ViewBag.dsdl = "active";
    ViewBag.nd = "Danh sách công nợ ";
    QuanLyDLproEntities2 db = new QuanLyDLproEntities2();

}
<link href="~/Content/KeToan/ketoan.css" rel="stylesheet" />
@{
    var checkmess = (string)TempData["edithd"];
    if (checkmess == "oke")
    {
        <script>
            swal({
                title: "Đã cập nhật đơn hàng thành công",
                icon: "success",
                button: "OK",
            });
        </script>
    }
}

<div class="row">
    <div class="col-md-12">
        <div class="tile">
            <div class="tile-body">
                <div class="btn-func col-sm-12" style="padding:10px;">
                    <div class="row">
                        <div class="col-sm-2">
                            <a class="btn btn-outline-dark btn-sm" role="button" title="In" onclick="printDiv('printhere')">
                                <i class="fas fa-print"></i> In dữ liệu
                            </a>
                        </div>
                        <div class="col-sm-2">
                            <a href="/KeToan/DSDaiLy" class="btn btn-warning btn-sm" type="button" title="Back">
                                Quay lại danh sách
                            </a>
                        </div>
                        <div class="col-sm-8">
                            @using (Html.BeginForm("DSCongnoNo", "KeToan", FormMethod.Post, new { @clas = "" }))
                            {
                                <div class="row">
                                    <div class="col-sm-2">
                                        @Html.DropDownList("thangs", (IEnumerable<SelectListItem>)TempData["thangs"], htmlAttributes: new { @class = "form-control-sm" })
                                    </div>
                                    <div class="col-sm-2">
                                        @Html.DropDownList("tinhtrangcn", (IEnumerable<SelectListItem>)TempData["tinhtrangcn"], htmlAttributes: new { @class = "form-control-sm", })
                                    </div>
                                    <div class="col-sm-2">
                                        <input type="submit" class="btn btn-danger btn-sm" value="Tìm theo tháng">
                                    </div>
                                </div>
                            }
                        </div>

                    </div>

                </div>

                <div class="row" id="printhere">
                    <div class="col-sm-12  table-responsive">
                        <table class="table table-hover table-bordered js-copytextarea dataTable no-footer" cellpadding="0" cellspacing="0" border="0" id="sampleTable" role="grid" aria-describedby="sampleTable_info">
                            @*//Phần render từng dòng trong C#*@
                            <thead>
                                <tr role="row">
                                    <th class="sorting" tabindex="0" aria-controls="sampleTable">Mã CN</th>
                                    <th class="sorting" tabindex="0" aria-controls="sampleTable">Tên đại lý</th>
                                    <th class="sorting" tabindex="0" aria-controls="sampleTable">Mã Đại lý</th>
                                    <th class="sorting" tabindex="0" aria-controls="sampleTable">Tổng nợ</th>
                                    <th class="sorting" tabindex="0" aria-controls="sampleTable">Ngày tạo phiếu</th>
                                    <th class="sorting" tabindex="0" aria-controls="sampleTable">Hạn trả</th>
                                    <th class="sorting" tabindex="0" aria-controls="sampleTable">Tình trạng</th>
                                    <th class="sorting" tabindex="0" aria-controls="sampleTable">Thanh toán</th>
                                    <th class="sorting" tabindex="0" aria-controls="sampleTable">Chức năng</th>
                                </tr>
                            </thead>

                            <tbody>
                                @foreach (var item in Model)
                                {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.MaCongNo)
                                    </td>
                                    <td>
                                        @{var tendl = db.DaiLies.Find(item.MaDL);
                                        }
                                        @Html.DisplayFor(modelItem => tendl.TenDL)

                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.MaDL)
                                    </td>
                                    <td>
                                        @{ var Tienno = string.Format("{0:0,0 vnđ}", item.TienNo);}
                                        @Html.DisplayFor(modelItem => Tienno)
                                    </td>
                                    <td>
                                        @{ var ngay = String.Format("{0:d/M/yyyy}", item.NgayLapCN); ;}
                                        @Html.DisplayFor(modelItem => ngay)
                                    </td>
                                    <td>
                                        @{ var han = String.Format("{0:d/M/yyyy}", item.HanTra);}
                                        @Html.DisplayFor(modelItem => han)
                                    </td>
                                    <td>
                                        @{
                                            DateTime aDatetime = DateTime.Now;
                                            DateTime hant = (DateTime)item.HanTra;
                                            TimeSpan interval = hant.Subtract(aDatetime);
                                           

                                            if (interval.Days <= 0)
                                            {
                                                <span class="badge badge-danger">Đến hạn</span>
                                            }
                                            else if (interval.Days > 0 && interval.Days <= 5)
                                            {
                                                <span class="badge badge-warning">Sắp đến hạn</span>
                                            }
                                            else
                                            {
                                                <span class="badge badge-success">Còn hạn</span>
                                            }

                                        }
                                    </td>
                                    <td>
                                        <p id="thanhtoan">
                                            @Html.DisplayFor(modelItem => item.TrangThai)
                                        </p>
                                    </td>
                                    <td>
                                        @*@{
            if (item.TrangThai == "Đã thanh toán")
            {
                <a href="javascript:void(0)" class="btn btn-outline-primary btn-sm ">
                    <i class="fa fa-edit"></i>
                </a>
            }
            else
            {
                <a href="/KeToan/ChinhsuCN/@item.MaCongNo" class="btn btn-outline-primary btn-sm ">
                    <i class="fa fa-edit"></i>
                </a>
            }
        }*@


                                        <a href="/KeToan/ChinhsuCN/@item.MaCongNo" class="btn btn-outline-primary btn-sm ">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                        <a href="/KeToan/ChitietCN/@item.MaCongNo" class="btn btn-outline-primary btn-sm ">
                                            <i class="fas fa-train"></i>
                                        </a>
                         

                                    </td>
                                </tr>
                                  
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>



    </div>
</div>
<script>
    function printDiv(divName) {

        var printContents = document.getElementById(divName).innerHTML;
        var originalContents = document.body.innerHTML;

        document.body.innerHTML = printContents;

        window.print();

        document.body.innerHTML = originalContents;


    }
    //function KiemtraThanhToan() {
    //    var value = document.getElementById("thanhtoan").innerHTML;
    //    if (value == "Chưa thanh toán") {
    //        //document.getElementById("checktt").disabled = false;

    //    }
    //    else {
    //        //document.getElementById("checktt").disabled = true;
    //        alert("Phiếu công nợ đã thanh toán !!");

    //    }

    
</script>

   

Test02/Views/KeToan/Doanhthu.cshtml
@model IEnumerable<Test02.Models.DonHang>

@{
    ViewBag.Title = "Doanh thu";
    Layout = "~/Views/KeToan/Layout/_LayoutPageKeToan.cshtml";
    ViewBag.dthu = "active";
    ViewBag.nd = "Báo cáo doanh thu";
}

<div class="row">
    <div class="col-md-12 container-fluid">
        <div class="tile">
            <div class="tile-body">
                <div class="row element-button" style="padding-left:10px">
                    <div class="col-sm-2">
                        <a class="btn btn-outline-dark btn-sm" type="button" title="In" onclick="printDiv('printme')">
                            <i class="fas fa-print"></i> In dữ liệu
                        </a>
                    </div>
                    <div class="col-sm-6">
                     @using (Html.BeginForm("Doanhthu", "KeToan", FormMethod.Post, new { @class = "form-group-sm" }))
                     {

                @Html.DropDownList("thangs", (IEnumerable<SelectListItem>)TempData["thangs"], htmlAttributes: new { @class = "form-control-sm" ,})
                <input type="submit" class="btn btn-danger btn-sm" value="Tìm theo tháng">


                     }
                    </div>
                </div>

                <div id="sampleTable_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4 no-footer">
                    @*<div class="row">
                        <div class="col-md-1">
                            <div id="sampleTable_filter" class="dataTables_filter">
                                <label>Tìm kiếm:<input type="search" class="form-control form-control-sm" placeholder="" aria-controls="sampleTable"></label>
                            </div>
                        </div>
                    </div>*@
                    <div class="row" id="printme">
                        <div class="col-sm-12  table-responsive">
                            <table class="table table-hover table-bordered js-copytextarea dataTable no-footer" cellpadding="0" cellspacing="0" border="0" id="sampleTable" role="grid" aria-describedby="sampleTable_info">
                                @*//Phần render từng dòng trong C#*@
                                <thead>
                                    <tr role="row">
                                        <th class="sorting" tabindex="0" aria-controls="sampleTable">Mã đơn hàng</th>
                                        <th class="sorting" tabindex="0" aria-controls="sampleTable">Mã đại lý</th>
                                        <th class="sorting" tabindex="0" aria-controls="sampleTable">Mã nhân viên lập</th>
                                        <th class="sorting" tabindex="0" aria-controls="sampleTable">Ngày lập</th>
                                        <th class="sorting" tabindex="0" aria-controls="sampleTable">Điểm giao hàng</th>
                                        <th class="sorting" tabindex="0" aria-controls="sampleTable">Tổng tiền</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @{ var total = 0;}
                                    @foreach (var item in Model)
                                    {
                     
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.MaDH)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.MaDL)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.MaNVLap)
                                        </td>
                                        @{ var ngay = String.Format("{0:d/M/yyyy}", item.NgayLap);}
                                        <td>
                                            @Html.DisplayFor(modelItem => ngay)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.DiemGiao)
                                        </td>
                                        <td>
                                            @{ total += Convert.ToInt32(item.TongTien);}
                                            @{ var ThanhTien = string.Format("{0:0,0 vnđ}", item.TongTien);}
                                            @Html.DisplayFor(modelItem => ThanhTien)

                                        </td>
                                    </tr>

                                                            

                                                        }
                                        <tr>
                                           
                                            <th colspan="5">Tổng cộng hóa đơn :</th>
                                            @{ var TongCong = string.Format("{0:0,0 vnđ}", total);}
                                            <td>@Html.DisplayFor(modelItem => TongCong)</td>
                                        </tr>
                                    </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    //In dữ liệu
    function printDiv(divName) {

        var printContents = document.getElementById(divName).innerHTML;
        var originalContents = document.body.innerHTML;

        document.body.innerHTML = printContents;

        window.print();

        document.body.innerHTML = originalContents;


    }
</script>

Test02/Views/KeToan/TaoCongno.cshtml
@model Test02.Models.DonHang
@using Test02.Models;

@{
    ViewBag.Title = "TaoCongno";
    Layout = "~/Views/KeToan/Layout/_LayoutPageKeToan.cshtml";
    QuanLyDLproEntities2 db = new QuanLyDLproEntities2();
    List<DonHang> dh = db.DonHangs.ToList();
    ViewBag.cn = "active";
    ViewBag.nd = "Tạo phiếu công nợ";
}



    <div class="row">
        <div class="col-md-12">
            <div class="tile">

                <h3 style="text-align:center">TẠO PHIẾU CÔNG NỢ</h3>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">

                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <p> <strong>Mã đại lý: </strong>@Html.DisplayFor(model => model.MaDL)</p>
                        @{
                            var tendl = db.DaiLies.Where(s => s.MaDL == Model.MaDL).FirstOrDefault();

                        }
                        <p><strong>Tên đại lý:</strong> @Html.DisplayFor(model => tendl.TenDL)</p>
                        <p><strong>Địa chỉ:</strong> @Html.DisplayFor(model => tendl.DiaChi)</p>
                        <p>
                            <strong>Loại đại lý:</strong> @{
                                var loai = db.LoaiDLs.Where(s => s.MaLoaiDL == tendl.MaLoaiDL).FirstOrDefault();
                            }@Html.DisplayFor(model => loai.TenDaiLy)
                        </p>

                        @{
                            int count = 0;
                            for (int i = 0; i < dh.Count; i++)
                            {

                                if (dh[i].TinhTrangThanhToan == "Chưa thanh toán" && Model.MaDL == dh[i].MaDL)
                                {
                                    count = (int)(count + dh[i].TongTien);

                                }
                            }
                            var Tienno = string.Format("{0:0,0 vnđ}", count);
                        }
                        <p><strong>Tiền nợ:</strong> @Html.DisplayFor(model => Tienno)</p>
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Thêm phiếu" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                }

                <div>
                    @Html.ActionLink("Quay lại danh sách đại lý", "DSDaily")
                </div>

            </div>
        </div>
    </div>

Test02/Views/KeToan/ThemCongno.cshtml
@model Test02.Models.PhieuCongNo

@{
    ViewBag.Title = "ThemCongno";
    Layout = "~/Views/KeToan/Layout/_LayoutPageKeToan.cshtml";
}

<h2>ThemCongno</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PhieuCongNo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        

        <div class="form-group">
            @Html.LabelFor(model => model.MaDL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaDL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaDL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TienNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TienNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TienNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HanTra, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HanTra, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HanTra, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TrangThai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TrangThai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TrangThai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm" class="btn btn-default" />
            </div>S
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại", "QLCongno")
</div>